name: Build
on: [push]
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: |
          docker build -t virtualbmc .
          docker run \
            --rm \
            --volume "$PWD:/host" \
            --entrypoint bash \
            virtualbmc \
            -c 'cp /packages/*.deb /host'
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Artifacts
          path: |
            *.deb
      - name: Login to the ${{ env.REGISTRY }} registry
        if: startsWith(github.ref, 'refs/tags/v')
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push image to the ${{ env.REGISTRY }} registry
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          IMAGE="${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${GITHUB_REF#refs/*/}"
          docker tag virtualbmc "$IMAGE"
          docker push "$IMAGE"
